# Generated by Django 5.0.6 on 2024-06-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=10, null=True)),
                ("height", models.FloatField(blank=True, max_length=10, null=True)),
                ("weight", models.FloatField(blank=True, max_length=10, null=True)),
                (
                    "exercise",
                    models.CharField(
                        choices=[
                            ("1", "幾乎不"),
                            ("2", "兩週一次"),
                            ("3", "一週一次"),
                            ("4", "一週三次"),
                            ("5", "每天"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
