# Generated by Django 5.0.6 on 2024-06-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("1", "早餐"),
                            ("2", "午餐"),
                            ("3", "晚餐"),
                            ("4", "宵夜"),
                            ("5", "零食"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "hungry",
                    models.CharField(
                        choices=[
                            ("1", "完全沒飽"),
                            ("2", "三分飽"),
                            ("3", "五分飽"),
                            ("4", "七分飽"),
                            ("5", "超級飽"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("food", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("1", "五榖根莖類"),
                            ("2", "蔬菜類"),
                            ("3", "水果類"),
                            ("4", "蛋豆魚肉類"),
                            ("5", "奶類"),
                            ("6", "油脂類"),
                        ],
                        max_length=200,
                    ),
                ),
                ("directions", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
