# Generated by Django 5.0.6 on 2024-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_todo_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="todo",
            name="category",
        ),
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.ManyToManyField(related_name="todos", to="todos.category"),
        ),
    ]
