# Generated by Django 5.0.6 on 2024-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_category_remove_todo_category_todo_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("1", "五榖根莖類"),
                    ("2", "蔬菜類"),
                    ("3", "水果類"),
                    ("4", "蛋豆魚肉類"),
                    ("5", "奶類"),
                    ("6", "油脂類"),
                ],
                max_length=200,
            ),
        ),
    ]
