# Generated by Django 5.0.6 on 2024-06-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0007_todo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
