# Generated by Django 5.0.6 on 2024-06-07 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0008_todo_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
