# Generated by Django 5.0.6 on 2024-06-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("1", "台式"),
                            ("2", "美式"),
                            ("3", "日式"),
                            ("4", "義式"),
                            ("5", "健康餐"),
                            ("6", "隨機"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
