# Generated by Django 5.0.6 on 2024-06-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0001_initial"),
        ("users", "0003_remove_user_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
    ]
