# Generated by Django 5.0.6 on 2024-06-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0002_menu_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
