# Generated by Django 5.0.6 on 2024-06-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0004_alter_menu_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
